# Generated by Django 5.1.4 on 2025-03-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medlink", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(null=True),
        ),
    ]
